version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Use the Node.js version your app requires
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Checking node_modules existence..."
      - ls -la node_modules | head -n 10
  
  build:
    commands:
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - echo "Checking current directory:"
      - pwd
      - echo "Listing files before build:"
      - ls -la
      - echo "Building the React app..."
      - npm run build
      - echo "Listing files after build:"
      - ls -la


  post_build:
    commands:
      - echo "Checking if build folder exists..."
      - ls -la build/
      # - echo Syncing build folder content to S3...
      # - aws s3 sync build/ s3://test.nfs-company.com --delete --exact-timestamps
      # - echo Invalidating CloudFront cache...
      # - aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
