version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Use the Node.js version your app requires
    commands:
      - echo Installing dependencies...
      - npm ci
  
  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo "Checking if build folder exists..."
      - ls -la build/
      # - echo Syncing build folder content to S3...
      # - aws s3 sync build/ s3://test.nfs-company.com --delete --exact-timestamps
      # - echo Invalidating CloudFront cache...
      # - aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
